name: tabletop_assistant
description: Project for FIT BUT KNN – Tabletop Assistant

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.13
  flutter_colorpicker: ^1.0.3
  url_launcher: ^6.1.0
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  dashboard: ^0.0.2+4
  flutter_reorderable_grid_view: ^3.1.3
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - 'assets/placeholder.png'
